#!/bin/bash -e

root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

main() {
    cd "$root"

    if [[ ! -e env ]]; then
        virtualenv env
        . env/bin/activate
        pip install websocket-client==0.40.0
    fi

    ./aoire.py "$@"
}

main "$@"
